# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4af4a4fa37890ac840dabe7a13e66524dc067284c91ccd5bf31bd472df7f2d5b8b1e34e919cc671b34798f379472cbc25c3c071f7c2c8f8e9ee46a463944b880

test:
  secret_key_base: ae08e801252b43f4df30de3d2250a7cb033ce264cc5a286d9a97e41cee10ee4497ca6ed99f94b611e460a88acd5f618dbb2578c20e00cc7530fe4ebe5aeb0724

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
